### ISSUE TITLE
Sent Message Confirmation

### ISSUE THREAD

**Issue by integraloftheday** [integraloftheday/Pebble-Imessager#3]
After sending a canned message there is no confirmation that the message was sent. Adding one would enable the user to be confident the message was sent properly.

**Comment by arcaderaid** [comment]
This would be great with the canned responses but also with the voice & keyboard replies. Thanks!

**Comment by integraloftheday** [comment]
Sounds good! I'll add the feature to all responses.

**Comment by integraloftheday** [comment]
The confirmation page was added see [release 1.6. ](https://github.com/integraloftheday/Pebble-Imessager/releases/tag/v1.6)

**Comment by arcaderaid** [comment]
I installed the update and it works, along with https://github.com/integraloftheday/Pebble-Imessager/issues/4 !  Thank you!  Note that I had to uninstall the previous version and reconfigure 1.6 as 1.5.1 was still present.
