### ISSUE TITLE
Return to buddy list after message confirmation 

### ISSUE THREAD

**Issue by arcaderaid** [integraloftheday/Pebble-Imessager#4]
After confirmation in https://github.com/integraloftheday/Pebble-Imessager/issues/3 , it would be nice to be returned to the buddy list, on the name of the person you just messaged. This would serve as an additional confirmation if user missed the sent animation.

**Comment by integraloftheday** [comment]
Thanks for the suggestion. I'll incorporate this into issue #3.

**Comment by integraloftheday** [comment]
The confirmation page was added see [release 1.6 ](https://github.com/integraloftheday/Pebble-Imessager/releases/tag/v1.6)in addition I made is so after the confirmation page was displayed it returned to the buddy list with the last person still selected. Thanks again for this suggestion!
