### ISSUE TITLE
Unable to send message to one self

### ISSUE THREAD

**Issue by arcaderaid** [integraloftheday/Pebble-Imessager#7]
Upon restarting my server and testing to make sure it's working, I attempted to sent a message to myself as I always do.  However, this time, I encountered an error:
_execution error: Messages got an error: Can't send a message to yourself._

I don't know if this is due to an iOS update or something with the app.  
iPhone 12 Mini, iOS 14.4

**Comment by integraloftheday** [comment]
I believe this is a problem with MacOS because I have randomly encountered the same issue. Does sending messages to other people still work?

**Comment by arcaderaid** [comment]
I can iMessage other people without any issues.  I'm using macOS Catalina 10.15.6.  I'll see if a reboot helps any.

**Comment by arcaderaid** [comment]
A reboot resolved the issue.  Bizarre!
