### ISSUE TITLE
Server cannot be reached on Pebble

### ISSUE THREAD

**Issue by tedosterone** [integraloftheday/Pebble-Imessager#9]
Hello! I've set up the server on my mac (currently running on Big Sur, if that's important) and I've completed all the steps for https setup, including going ahead and locking the IP address for port forwarding. I've given the certificate full trust for root access and I've double checked on the web browser that it's working and receive the URL not found error along with a line of fetch data in the server which appears as
`::ffff:192.168.1.149 - - [2021-04-13 12:36:58] "GET / HTTP/1.1" 404 356 0.002893`

I've taken this as my go ahead that the server is running and everything is all fine and good, but my watch still won't connect. I'll enter my local IP and the port in the Server IP and will enter the key generated by the watch in config.json but when I select Data Fetch I receive an error saying the server cannot be reached and to check the entered Server IP. 

I'd attach the code the server shows when I attempt to connect but it doesn't show anything whenever I try to connect the watch. Should I still be entering the local IP and port when trying to connect to the Server, or is there a different IP Address that I'm just missing?

**Comment by integraloftheday** [comment]
I believe Big Sur could have removed the messaging protocol used in the server back end to send the iMessage. I have not yet been able to test this but you can do so by trying to run the following command. 

`osascript -e 'tell application "Messages" to send "Test" to buddy "<Some Contact Name>"`


If the command above works you can look at why its not connecting to the server. Are you inputting your local IP into the watch or the public IP?

**Comment by michaellunzer** [comment]
Any update on if this works on Big Sur and beyond?

**Comment by michaellunzer** [comment]
> Any update on if this works on Big Sur and beyond?

I can confirm this works on a Monterey MacOS virtual machine!

**Comment by integraloftheday** [comment]
Thanks for validating this! I didn't have a machine that worked past Catalina, so I was never able to verify it.
